services:
  # --------------------
  # 前端 Vue 開發模式
  # --------------------
  frontend:
    build: ./frontend        # 前端 Dockerfile 路徑
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - member-net

  # --------------------
  # 後端 FastAPI
  # --------------------
  backend:
    build: ./backend         # 後端 Dockerfile 路徑
    ports:
      - "8080:8080"          # 本地 8080 對應容器內 8080 (FastAPI uvicorn)
    env_file:
      - .env                  # 從 .env 讀取環境變數
    volumes:
      - ./backend:/app  # 讓程式碼變動能即時反應（開發常用）
      - ./gcp-key.json:/app/gcp-key.json  # 將根目錄的金鑰掛到容器內
    environment:
      # 在這裡強制指定 Google SDK 要去哪裡找金鑰
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
    depends_on:
      - mysql
    networks:
      - member-net

  # --------------------
  # MySQL 資料庫 (官方 image)
  # --------------------
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env       # 從 .env 讀取 MySQL root 密碼、資料庫名稱
    # **** 新增此區塊來強制設定編碼 ****
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    # **********************************
    volumes:
      # 將初始化 SQL 檔案掛載進去
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # 掛載測試資料檔案
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - member-net

# --------------------
# Volume
# --------------------
volumes:
  mysql-data:

# --------------------
# Network
# --------------------
networks:
  member-net:
    driver: bridge